table Suppliers
	lineageTag: 1bf26885-dc8d-4bcb-9fd9-8dbfdcf2d816

	column Column1
		dataType: string
		lineageTag: 3633b3b0-9c47-4605-8fd7-8e982bc7636b
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column 'Prime ICT Supplier Name'
		dataType: string
		lineageTag: f4bea48f-59ac-49f4-bf18-870a144bbd92
		summarizeBy: none
		sourceColumn: Prime ICT Supplier Name

		annotation SummarizationSetBy = Automatic

	column 'Prime ICT Supplier Capability Type'
		dataType: string
		lineageTag: 5d4e4dec-185d-440d-874c-33a15d400041
		summarizeBy: none
		sourceColumn: Prime ICT Supplier Capability Type

		annotation SummarizationSetBy = Automatic

	column 'Supplier ID'
		dataType: string
		lineageTag: 7fabc0c4-cbb8-4b8e-b80d-1bcf40da0a64
		summarizeBy: none
		sourceColumn: Supplier ID

		annotation SummarizationSetBy = Automatic

	column PostCode
		dataType: string
		lineageTag: cc080646-73f9-4eaf-8d6b-782f7aaac972
		summarizeBy: none
		sourceColumn: PostCode

		annotation SummarizationSetBy = Automatic

	partition Suppliers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\OneDrive_plarchi\OneDrive - connect.hku.hk\Data_Engineering\MsC_Edinburgh\XL002942_Business_Intelligence\Coursework_2\PowerBI\Coursework Dataset v1.0_Clean.xlsx"), null, true),
				    Suppliers_Sheet = Source{[Item="Suppliers",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Suppliers_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Top Rows",{{"Column5", "PostCode"}, {"Column4", "Supplier ID"}, {"Column3", "Prime ICT Supplier Capability Type"}, {"Column2", "Prime ICT Supplier Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

